name: brogue-ce
summary: Welcome to the Dungeons of Doom!
description: Brogue is a single-player strategy game set in the halls of a mysterious and randomly-generated dungeon.
license: AGPL-3.0

adopt-info: brogue-ce
confinement: strict
base: core18

parts:
  brogue-ce:
    source: .
    plugin: make

    override-pull: |
      snapcraftctl pull
      version="$(git describe --always | sed -e 's/-/+git/;y/-/./')"
      [ -n "$(echo $version | grep "+git")" ] && grade=devel || grade=stable
      snapcraftctl set-version "$version"
      snapcraftctl set-grade "$grade"

    override-build: |
      # Build and install brogue
      make clean && make DATADIR='\$$SNAP/usr/share' && make install DESTDIR=$SNAPCRAFT_PART_INSTALL &&

      # Configure wrapper to run brogue from user data directory
      echo 'cd $SNAP_USER_DATA && brogue "$@"' >> $SNAPCRAFT_PART_INSTALL/usr/bin/brogue-wrapper &&
      chmod +x $SNAPCRAFT_PART_INSTALL/usr/bin/brogue-wrapper

    build-packages:
      - build-essential
      - git
      - libsdl2-dev
      - libsdl2-image-dev

    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0

apps:
  brogue-ce:
    command: brogue-wrapper
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
