name: "Build"
on:
  push:

jobs:

  linux:
    runs-on: ubuntu-16.04
    steps:
    - name: "Install dependencies"
      run: |
        sudo apt install -y libsdl2-dev libsdl2-image-dev

    - name: "Checkout sources"
      uses: actions/checkout@v2

    - name: "Compile"
      run: |
        make bin/brogue

    - name: "Upload artifact"
      uses: actions/upload-artifact@v1
      with:
        name: linux-bin
        path: bin

  macos:
    runs-on: macos-latest
    steps:
    - name: "Checkout sources"
      uses: actions/checkout@v2

    - name: "Compile and install dependencies"
      run: |
        brew install macos/sdl2.rb sdl2_image dylibbundler

    - name: "Compile"
      run: |
        make MAC_APP=YES Brogue.app
      env:
        # 10.6 is the version targeted by the SDL build scripts
        MACOSX_DEPLOYMENT_TARGET: "10.6"

    - name: "Fix and bundle dylib references"
      run: |
        cd Brogue.app/Contents && dylibbundler -cd -b -x MacOS/brogue

    - name: "Upload artifact"
      uses: actions/upload-artifact@v1
      with:
        name: Brogue.app
        path: Brogue.app

  windows:
    runs-on: windows-latest
    steps:
    - name: "Checkout sources"
      uses: actions/checkout@v2
    - name: "Install dependencies"
      run: |
        .\.github\get-deps-mingw.ps1
    - name: "Compile"
      shell: powershell
      run: |
        $env:path = $env:path + ";" + (Join-Path $pwd.Drive.Root "opt/local/x86_64-w64-mingw32/bin")
        mingw32-make CC=gcc bin/brogue.exe
    - name: "Package"
      run: |
        cp .\SDL2\x86_64-w64-mingw32\bin\SDL2.dll .\bin\
        cp .\SDL2_image\x86_64-w64-mingw32\bin\zlib1.dll .\bin\
        cp .\SDL2_image\x86_64-w64-mingw32\bin\SDL2_image.dll .\bin\
        cp .\SDL2_image\x86_64-w64-mingw32\bin\libpng16-16.dll .\bin\
    - name: "Upload artifact"
      uses: actions/upload-artifact@v1
      with:
        name: windows-mingw-bin
        path: bin

  snap:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v1
      with:
        snapcraft_token: ${{ secrets.snapcraft_token }}

    - name: Build snap
      run: snapcraft --destructive-mode

    - name: "Upload artifact"
      uses: actions/upload-artifact@v2
      with:
        path: "*.snap"
        name: brogue.snap

    - name: Publish development snap
      if: github.ref == 'refs/heads/master'
      run: snapcraft push --release edge *.snap

    - name: Publish release snap
      if: startsWith(github.ref, 'refs/tags/g')
      run: snapcraft push --release beta *.snap
